version: '3'
services:
    postgresql:
      image: 'whoatedacakeidid/processing-postgres:latest'
      ports:
        - "${PG_PORT}:${PG_PORT}"
      environment:
        - "POSTGRES_USER=${PG_USER}"
        - "POSTGRES_PASSWORD=${PG_PASSWORD}"
        - "POSTGRES_DB=${PG_DB}"
      volumes:
        - postgresql:/var/lib/postgresql/data


volumes:
    postgresql: {}

